### ISSUE TITLE
Warning in Ch_18

### ISSUE THREAD

**Issue by StrangeTcy** [CorticalComputer/Book_NeuroevolutionThroughErlang#4]
When trying to `make:all([load]).` the source code for Ch_18, I get a lot of warnings about unused variables and some methods being deprecated. Since I'm not that good with Erlang yet, I wonder whether I can safely ignore those warnings or are they a sign of an actual problem.

**Comment by CorticalComputer** [comment]
You can safely ignore the warnings. They are primarily there to remind you
that those unused variables can be modified later on to augment the way the
system functions. The shared source code for the book, as is, is in
perfectly working order. I ran every piece of that code as I wrote the book
chapters, as can be seen from the actual chapters and the demonstration of
the result of running the code. So you can follow the chapters and use the
code together, seamlessly.

**Comment by CorticalComputer** [comment]
With regards to deprecated methods, it is primarily due to the more recent
updates done to Erlang. As Erlang changes, they are of course deprecating
some of the functions, and adding new ones. For example, Erlang has moved
away from its own graphical module, and is now using a different one... but
the old one, though deprecated, is still functional.

**Comment by StrangeTcy** [comment]
Thanks.
I was actually able to run all the code, so that wasn't an issue. These warnings just appeared somewhat worrying.
