### ISSUE TITLE
Polises

### ISSUE THREAD

**Issue by StrangeTcy** [CorticalComputer/Book_NeuroevolutionThroughErlang#5]
This is not an issue but more of a question; are there any plans on implementing multiple polises that would work on different machines (real or virtual) and talk to each other? I wonder if it's hard to write.

**Comment by CorticalComputer** [comment]
The system architecture was actually made to run with multiple polises in
parallel, and indeed to even allow the agents to move from one polis to
another, if their morphology allows it. Though it is up to you to create
new sensors and actuators for your agents, so that they can move between
the various polises, and how fitness is handled when this is done. To
architecture this, you simply spawn your polises on multiple machines, you
can then either allow for the same database to be shared between them, or
for each polis to have a separate database, with an agent transference
handshake protocol.

The DXNN architecture was created for the purpose of evolving ever more
complex computational intelligence. If you can tie in a physics engine and
high fidelity and high level granularity environment scape, more complex
agents will evolve, as compared to the already highly organic and
biologically feasible behaviors that was evolved very rapidly in the
flatland scape.

**Comment by StrangeTcy** [comment]
Thanks! If I ever get to implement such simulations, I'd most likely share.
